spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 2659201192
    url: jdbc:mysql://8.130.77.175:3306/mall?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&userSSL=true&serverTimeZone=Asia/shanghai
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: guest
    password: guest
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml
wx:
  appid: wx3e6b9f1c5a7ff034
  mchId: 1614433647
  mchKey: Aa111111111122222222223333333333
  notifyUrl: http://8.130.77.175/pay/notify
  returnUrl: http://8.130.77.175/#/order/list


